// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace AiAssistant.ApplicationService.Persistence.Migrations;

[DbContext(typeof(AiAssistantDbContext))]
partial class AiAssistantDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("AiAssistant.ApplicationService.Entities.AiLead", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

            b.Property<string>("PhoneNumber")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("nvarchar(32)");
            b.Property<DateTime>("ReceivedAt").HasColumnType("datetime2");
            b.Property<string>("ReportDescription").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<DateTime?>("ReportSubmittedAt").HasColumnType("datetime2");
            b.Property<long>("SourceLeadAssignmentId").HasColumnType("bigint");
            b.Property<string>("UserName").HasMaxLength(200).HasColumnType("nvarchar(200)");

            b.HasKey("Id");
            b.HasIndex("SourceLeadAssignmentId").IsUnique();
            b.ToTable("AiLeads");
        });
#pragma warning restore 612, 618
    }
}
